import type { EdTechTool } from './types'

export const SAMPLE_EDTECH_TOOLS: EdTechTool[] = [
  {
    id: 'tool-epaath-01',
    name: 'OLE Nepal E-Paath',
    description:
      'Interactive digital learning activities aligned with Nepal national curriculum for Grades 1–8. Works completely offline on school servers or low-spec devices.',
    category: 'Curriculum & Interactive Learning',
    bandwidthRequirement: 'offline',
    costModel: 'free',
    costUsdPerStudentYear: null,
    deploymentMode: 'offline_capable',
    supportsLowBandwidth: true,
    nepaliLanguageSupport: true,
    minimumDeviceSpec: 'basic',
    teacherTrainingDaysRequired: 2,
    onlineSupportAvailable: false,
    infrastructureRequirement: 1, // works even with minimal infrastructure
    teacherReadinessRequirement: 2,
  },
  {
    id: 'tool-khan-02',
    name: 'Khan Academy / Khan Academy Kids',
    description:
      'Free, world-class math, science, and literacy content with teacher dashboard for student progress tracking.',
    category: 'STEM & Self-Paced Learning',
    bandwidthRequirement: 'medium',
    costModel: 'free',
    costUsdPerStudentYear: null,
    deploymentMode: 'both',
    supportsLowBandwidth: true,
    nepaliLanguageSupport: false,
    minimumDeviceSpec: 'mid',
    teacherTrainingDaysRequired: 3,
    onlineSupportAvailable: true,
    infrastructureRequirement: 3,
    teacherReadinessRequirement: 3,
  },
  {
    id: 'tool-kolibri-03',
    name: 'Kolibri Offline Learning Platform',
    description:
      'Open-source educational platform designed to provide offline access to a curated library of open educational resources in low-resource contexts.',
    category: 'Offline Learning Management System',
    bandwidthRequirement: 'offline',
    costModel: 'free',
    costUsdPerStudentYear: null,
    deploymentMode: 'offline_capable',
    supportsLowBandwidth: true,
    nepaliLanguageSupport: true,
    minimumDeviceSpec: 'basic',
    teacherTrainingDaysRequired: 3,
    onlineSupportAvailable: false,
    infrastructureRequirement: 1,
    teacherReadinessRequirement: 2,
  },
  {
    id: 'tool-gclassroom-04',
    name: 'Google Classroom & Workspace for Education',
    description:
      'Cloud-based learning management system for assignment distribution, grading, and communication.',
    category: 'Learning Management System (LMS)',
    bandwidthRequirement: 'high',
    costModel: 'free',
    costUsdPerStudentYear: null,
    deploymentMode: 'web',
    supportsLowBandwidth: false,
    nepaliLanguageSupport: false,
    minimumDeviceSpec: 'mid',
    teacherTrainingDaysRequired: 5,
    onlineSupportAvailable: true,
    infrastructureRequirement: 4,
    teacherReadinessRequirement: 4,
  },
  {
    id: 'tool-duolingo-05',
    name: 'Duolingo for Schools',
    description:
      'Gamified language learning platform with teacher control panel to track student vocabulary and grammar progress.',
    category: 'Language Learning',
    bandwidthRequirement: 'low',
    costModel: 'free',
    costUsdPerStudentYear: null,
    deploymentMode: 'app',
    supportsLowBandwidth: true,
    nepaliLanguageSupport: false,
    minimumDeviceSpec: 'basic',
    teacherTrainingDaysRequired: 1,
    onlineSupportAvailable: true,
    infrastructureRequirement: 2,
    teacherReadinessRequirement: 2,
  },
]
